import { CriteriaResult, PathwayResults } from 'pathways-model';

export const resources: fhir.DomainResource[] = [
  {
    resourceType: 'Patient',
    id: '126040',
    meta: {
      versionId: '1',
      lastUpdated: '2019-08-22T17:03:11.110+00:00',
      profile: ['http://hl7.org/fhir/us/shr/DSTU2/StructureDefinition/shr-core-Patient']
    },
    text: {
      status: 'generated',
      div:
        '<div xmlns="http://www.w3.org/1999/xhtml">Generated by <a href="https://github.com/synthetichealth/synthea">Synthea</a>.Version identifier: v2.4.0-280-g8074e2b4\n .   Person seed: -7317590361990904573  Population seed: 1564681358627</div>'
    }
  }
];

export const evaluatedCriteria: CriteriaResult[] = [
  {
    pathwayName: 'test1',
    matches: 1,
    criteriaResultItems: [
      {
        elementName: 'condition',
        expected: 'breast Cancer',
        actual: 'Malignant neoplasm of breast (disorder)',
        match: true
      }
    ]
  },
  {
    pathwayName: 'test2',
    matches: 0,
    criteriaResultItems: [
      {
        elementName: 'condition',
        expected: 'gist Cancer',
        actual: 'Malignant neoplasm of breast (disorder)',
        match: false
      }
    ]
  },
  {
    pathwayName: 'test3',
    matches: 0,
    criteriaResultItems: [
      {
        elementName: 'condition',
        expected: 'lung Cancer',
        actual: 'Malignant neoplasm of breast (disorder)',
        match: false
      }
    ]
  }
];

export const evaluatedPathwayResults: PathwayResults = {
  patientId: '1',
  currentState: 'Start',
  currentStatus: 'not-done',
  nextRecommendation: 'T-test',
  documentation: [],
  path: ['Start']
};
